// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package net.malta.model;

/**
 * 
 */
public abstract class DbFile
    implements java.io.Serializable
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 7105237568785211304L;

    private java.lang.Integer id;

    /**
     * 
     */
    public java.lang.Integer getId()
    {
        return this.id;
    }

    public void setId(java.lang.Integer id)
    {
        this.id = id;
    }

    private byte[] data;

    /**
     * 
     */
    public byte[] getData()
    {
        return this.data;
    }

    public void setData(byte[] data)
    {
        this.data = data;
    }

    /**
     * Returns <code>true</code> if the argument is an DbFile instance and all identifiers for this entity
     * equal the identifiers of the argument entity. Returns <code>false</code> otherwise.
     */
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof DbFile))
        {
            return false;
        }
        final DbFile that = (DbFile)object;
        if (this.id == null || that.getId() == null || !this.id.equals(that.getId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code based on this entity's identifiers.
     */
    public int hashCode()
    {
        int hashCode = 0;
        hashCode = 29 * hashCode + (id == null ? 0 : id.hashCode());

        return hashCode;
    }

    /**
     * Constructs new instances of {@link net.malta.model.DbFile}.
     */
    public static final class Factory
    {
        /**
         * Constructs a new instance of {@link net.malta.model.DbFile}.
         */
        public static net.malta.model.DbFile newInstance()
        {
            return new net.malta.model.DbFileImpl();
        }


        /**
         * Constructs a new instance of {@link net.malta.model.DbFile}, taking all possible properties
         * (except the identifier(s))as arguments.
         */
        public static net.malta.model.DbFile newInstance(byte[] data)
        {
            final net.malta.model.DbFile entity = new net.malta.model.DbFileImpl();
            entity.setData(data);
            return entity;
        }
    }
    
// HibernateEntity.vsl merge-point
}