// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package net.malta.model;

/**
 * 
 */
public abstract class Prefecture
    implements java.io.Serializable
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 3024986557035256947L;

    private java.lang.Integer id;

    /**
     * 
     */
    public java.lang.Integer getId()
    {
        return this.id;
    }

    public void setId(java.lang.Integer id)
    {
        this.id = id;
    }

    private java.lang.String name;

    /**
     * 
     */
    public java.lang.String getName()
    {
        return this.name;
    }

    public void setName(java.lang.String name)
    {
        this.name = name;
    }

    private java.util.Collection publicUsers = new java.util.HashSet();

    /**
     * 
     */
    public java.util.Collection getPublicUsers()
    {
        return this.publicUsers;
    }

    public void setPublicUsers(java.util.Collection publicUsers)
    {
        this.publicUsers = publicUsers;
    }

    private java.util.Collection deliveryAddresses = new java.util.HashSet();

    /**
     * 
     */
    public java.util.Collection getDeliveryAddresses()
    {
        return this.deliveryAddresses;
    }

    public void setDeliveryAddresses(java.util.Collection deliveryAddresses)
    {
        this.deliveryAddresses = deliveryAddresses;
    }

    /**
     * Returns <code>true</code> if the argument is an Prefecture instance and all identifiers for this entity
     * equal the identifiers of the argument entity. Returns <code>false</code> otherwise.
     */
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof Prefecture))
        {
            return false;
        }
        final Prefecture that = (Prefecture)object;
        if (this.id == null || that.getId() == null || !this.id.equals(that.getId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code based on this entity's identifiers.
     */
    public int hashCode()
    {
        int hashCode = 0;
        hashCode = 29 * hashCode + (id == null ? 0 : id.hashCode());

        return hashCode;
    }

    /**
     * Constructs new instances of {@link net.malta.model.Prefecture}.
     */
    public static final class Factory
    {
        /**
         * Constructs a new instance of {@link net.malta.model.Prefecture}.
         */
        public static net.malta.model.Prefecture newInstance()
        {
            return new net.malta.model.PrefectureImpl();
        }

        /**
         * Constructs a new instance of {@link net.malta.model.Prefecture}, taking all required and/or
         * read-only properties as arguments.
         */
        public static net.malta.model.Prefecture newInstance(java.lang.String name)
        {
            final net.malta.model.Prefecture entity = new net.malta.model.PrefectureImpl();
            entity.setName(name);
            return entity;
        }

        /**
         * Constructs a new instance of {@link net.malta.model.Prefecture}, taking all possible properties
         * (except the identifier(s))as arguments.
         */
        public static net.malta.model.Prefecture newInstance(java.lang.String name, java.util.Collection publicUsers, java.util.Collection deliveryAddresses)
        {
            final net.malta.model.Prefecture entity = new net.malta.model.PrefectureImpl();
            entity.setName(name);
            entity.setPublicUsers(publicUsers);
            entity.setDeliveryAddresses(deliveryAddresses);
            return entity;
        }
    }
    
// HibernateEntity.vsl merge-point
}