// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SpringHibernateDaoBase.vsl in andromda-spring-cartridge.
//
package net.malta.model;

/**
 * <p>
 * Base Spring DAO Class: is able to create, update, remove, load, and find
 * objects of type <code>net.malta.model.Category</code>.
 * </p>
 *
 * @see net.malta.model.Category
 */
public abstract class CategoryDaoBase
    extends org.springframework.orm.hibernate3.support.HibernateDaoSupport
    implements net.malta.model.CategoryDao
{

    /**
     * @see net.malta.model.CategoryDao#load(int, java.lang.Integer)
     */
    public java.lang.Object load(final int transform, final java.lang.Integer id)
    {
        if (id == null)
        {
            throw new IllegalArgumentException(
                "Category.load - 'id' can not be null");
        }
        final java.lang.Object entity = this.getHibernateTemplate().get(net.malta.model.CategoryImpl.class, id);
        return transformEntity(transform, (net.malta.model.Category)entity);
    }

    /**
     * @see net.malta.model.CategoryDao#load(java.lang.Integer)
     */
    public net.malta.model.Category load(java.lang.Integer id)
    {
        return (net.malta.model.Category)this.load(TRANSFORM_NONE, id);
    }

    /**
     * @see net.malta.model.CategoryDao#loadAll()
     */
    public java.util.Collection loadAll()
    {
        return this.loadAll(TRANSFORM_NONE);
    }

    /**
     * @see net.malta.model.CategoryDao#loadAll(int)
     */
    public java.util.Collection loadAll(final int transform)
    {
        final java.util.Collection results = this.getHibernateTemplate().loadAll(net.malta.model.CategoryImpl.class);
        this.transformEntities(transform, results);
        return results;
    }


    /**
     * @see net.malta.model.CategoryDao#create(net.malta.model.Category)
     */
    public net.malta.model.Category create(net.malta.model.Category category)
    {
        return (net.malta.model.Category)this.create(TRANSFORM_NONE, category);
    }

    /**
     * @see net.malta.model.CategoryDao#create(int transform, net.malta.model.Category)
     */
    public java.lang.Object create(final int transform, final net.malta.model.Category category)
    {
        if (category == null)
        {
            throw new IllegalArgumentException(
                "Category.create - 'category' can not be null");
        }
        this.getHibernateTemplate().save(category);
        return this.transformEntity(transform, category);
    }

    /**
     * @see net.malta.model.CategoryDao#create(java.util.Collection)
     */
    public java.util.Collection create(final java.util.Collection entities)
    {
        return create(TRANSFORM_NONE, entities);
    }

    /**
     * @see net.malta.model.CategoryDao#create(int, java.util.Collection)
     */
    public java.util.Collection create(final int transform, final java.util.Collection entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "Category.create - 'entities' can not be null");
        }
        this.getHibernateTemplate().execute(
            new org.springframework.orm.hibernate3.HibernateCallback()
            {
                public java.lang.Object doInHibernate(org.hibernate.Session session)
                    throws org.hibernate.HibernateException
                {
                    for (java.util.Iterator entityIterator = entities.iterator(); entityIterator.hasNext();)
                    {
                        create(transform, (net.malta.model.Category)entityIterator.next());
                    }
                    return null;
                }
            },
            true);
        return entities;
    }

    /**
     * @see net.malta.model.CategoryDao#create(java.lang.String)
     */
    public net.malta.model.Category create(
        java.lang.String name)
    {
        return (net.malta.model.Category)this.create(TRANSFORM_NONE, name);
    }

    /**
     * @see net.malta.model.CategoryDao#create(int, java.lang.String)
     */
    public java.lang.Object create(
        final int transform,
        java.lang.String name)
    {
        net.malta.model.Category entity = new net.malta.model.CategoryImpl();
        entity.setName(name);
        return this.create(transform, entity);
    }

    /**
     * @see net.malta.model.CategoryDao#update(net.malta.model.Category)
     */
    public void update(net.malta.model.Category category)
    {
        if (category == null)
        {
            throw new IllegalArgumentException(
                "Category.update - 'category' can not be null");
        }
        this.getHibernateTemplate().update(category);
    }

    /**
     * @see net.malta.model.CategoryDao#update(java.util.Collection)
     */
    public void update(final java.util.Collection entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "Category.update - 'entities' can not be null");
        }
        this.getHibernateTemplate().execute(
            new org.springframework.orm.hibernate3.HibernateCallback()
            {
                public java.lang.Object doInHibernate(org.hibernate.Session session)
                    throws org.hibernate.HibernateException
                {
                    for (java.util.Iterator entityIterator = entities.iterator(); entityIterator.hasNext();)
                    {
                        update((net.malta.model.Category)entityIterator.next());
                    }
                    return null;
                }
            },
            true);
    }

    /**
     * @see net.malta.model.CategoryDao#remove(net.malta.model.Category)
     */
    public void remove(net.malta.model.Category category)
    {
        if (category == null)
        {
            throw new IllegalArgumentException(
                "Category.remove - 'category' can not be null");
        }
        this.getHibernateTemplate().delete(category);
    }

    /**
     * @see net.malta.model.CategoryDao#remove(java.lang.Integer)
     */
    public void remove(java.lang.Integer id)
    {
        if (id == null)
        {
            throw new IllegalArgumentException(
                "Category.remove - 'id' can not be null");
        }
        net.malta.model.Category entity = this.load(id);
        if (entity != null)
        {
            this.remove(entity);
        }
    }

    /**
     * @see net.malta.model.CategoryDao#remove(java.util.Collection)
     */
    public void remove(java.util.Collection entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "Category.remove - 'entities' can not be null");
        }
        this.getHibernateTemplate().deleteAll(entities);
    }
    /**
     * Allows transformation of entities into value objects
     * (or something else for that matter), when the <code>transform</code>
     * flag is set to one of the constants defined in <code>net.malta.model.CategoryDao</code>, please note
     * that the {@link #TRANSFORM_NONE} constant denotes no transformation, so the entity itself
     * will be returned.
     *
     * If the integer argument value is unknown {@link #TRANSFORM_NONE} is assumed.
     *
     * @param transform one of the constants declared in {@link net.malta.model.CategoryDao}
     * @param entity an entity that was found
     * @return the transformed entity (i.e. new value object, etc)
     * @see #transformEntities(int,java.util.Collection)
     */
    protected java.lang.Object transformEntity(final int transform, final net.malta.model.Category entity)
    {
        java.lang.Object target = null;
        if (entity != null)
        {
            switch (transform)
            {
                case TRANSFORM_NONE : // fall-through
                default:
                    target = entity;
            }
        }
        return target;
    }

    /**
     * Transforms a collection of entities using the
     * {@link #transformEntity(int,net.malta.model.Category)}
     * method. This method does not instantiate a new collection.
     * <p/>
     * This method is to be used internally only.
     *
     * @param transform one of the constants declared in <code>net.malta.model.CategoryDao</code>
     * @param entities the collection of entities to transform
     * @see #transformEntity(int,net.malta.model.Category)
     */
    protected void transformEntities(final int transform, final java.util.Collection entities)
    {
        switch (transform)
        {
            case TRANSFORM_NONE : // fall-through
                default:
                // do nothing;
        }
    }

}