// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SpringHibernateDaoBase.vsl in andromda-spring-cartridge.
//
package net.malta.model;

/**
 * <p>
 * Base Spring DAO Class: is able to create, update, remove, load, and find
 * objects of type <code>net.malta.model.DeliveryAddressChoise</code>.
 * </p>
 *
 * @see net.malta.model.DeliveryAddressChoise
 */
public abstract class DeliveryAddressChoiseDaoBase
    extends org.springframework.orm.hibernate3.support.HibernateDaoSupport
    implements net.malta.model.DeliveryAddressChoiseDao
{

    /**
     * @see net.malta.model.DeliveryAddressChoiseDao#load(int, java.lang.Integer)
     */
    public java.lang.Object load(final int transform, final java.lang.Integer id)
    {
        if (id == null)
        {
            throw new IllegalArgumentException(
                "DeliveryAddressChoise.load - 'id' can not be null");
        }
        final java.lang.Object entity = this.getHibernateTemplate().get(net.malta.model.DeliveryAddressChoiseImpl.class, id);
        return transformEntity(transform, (net.malta.model.DeliveryAddressChoise)entity);
    }

    /**
     * @see net.malta.model.DeliveryAddressChoiseDao#load(java.lang.Integer)
     */
    public net.malta.model.DeliveryAddressChoise load(java.lang.Integer id)
    {
        return (net.malta.model.DeliveryAddressChoise)this.load(TRANSFORM_NONE, id);
    }

    /**
     * @see net.malta.model.DeliveryAddressChoiseDao#loadAll()
     */
    public java.util.Collection loadAll()
    {
        return this.loadAll(TRANSFORM_NONE);
    }

    /**
     * @see net.malta.model.DeliveryAddressChoiseDao#loadAll(int)
     */
    public java.util.Collection loadAll(final int transform)
    {
        final java.util.Collection results = this.getHibernateTemplate().loadAll(net.malta.model.DeliveryAddressChoiseImpl.class);
        this.transformEntities(transform, results);
        return results;
    }


    /**
     * @see net.malta.model.DeliveryAddressChoiseDao#create(net.malta.model.DeliveryAddressChoise)
     */
    public net.malta.model.DeliveryAddressChoise create(net.malta.model.DeliveryAddressChoise deliveryAddressChoise)
    {
        return (net.malta.model.DeliveryAddressChoise)this.create(TRANSFORM_NONE, deliveryAddressChoise);
    }

    /**
     * @see net.malta.model.DeliveryAddressChoiseDao#create(int transform, net.malta.model.DeliveryAddressChoise)
     */
    public java.lang.Object create(final int transform, final net.malta.model.DeliveryAddressChoise deliveryAddressChoise)
    {
        if (deliveryAddressChoise == null)
        {
            throw new IllegalArgumentException(
                "DeliveryAddressChoise.create - 'deliveryAddressChoise' can not be null");
        }
        this.getHibernateTemplate().save(deliveryAddressChoise);
        return this.transformEntity(transform, deliveryAddressChoise);
    }

    /**
     * @see net.malta.model.DeliveryAddressChoiseDao#create(java.util.Collection)
     */
    public java.util.Collection create(final java.util.Collection entities)
    {
        return create(TRANSFORM_NONE, entities);
    }

    /**
     * @see net.malta.model.DeliveryAddressChoiseDao#create(int, java.util.Collection)
     */
    public java.util.Collection create(final int transform, final java.util.Collection entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "DeliveryAddressChoise.create - 'entities' can not be null");
        }
        this.getHibernateTemplate().execute(
            new org.springframework.orm.hibernate3.HibernateCallback()
            {
                public java.lang.Object doInHibernate(org.hibernate.Session session)
                    throws org.hibernate.HibernateException
                {
                    for (java.util.Iterator entityIterator = entities.iterator(); entityIterator.hasNext();)
                    {
                        create(transform, (net.malta.model.DeliveryAddressChoise)entityIterator.next());
                    }
                    return null;
                }
            },
            true);
        return entities;
    }

    /**
     * @see net.malta.model.DeliveryAddressChoiseDao#create(int, java.lang.String, java.lang.String)
     */
    public net.malta.model.DeliveryAddressChoise create(
        int ordernum,
        java.lang.String preferreddate,
        java.lang.String preferredtime)
    {
        return (net.malta.model.DeliveryAddressChoise)this.create(TRANSFORM_NONE, ordernum, preferreddate, preferredtime);
    }

    /**
     * @see net.malta.model.DeliveryAddressChoiseDao#create(int, int, java.lang.String, java.lang.String)
     */
    public java.lang.Object create(
        final int transform,
        int ordernum,
        java.lang.String preferreddate,
        java.lang.String preferredtime)
    {
        net.malta.model.DeliveryAddressChoise entity = new net.malta.model.DeliveryAddressChoiseImpl();
        entity.setOrdernum(ordernum);
        entity.setPreferreddate(preferreddate);
        entity.setPreferredtime(preferredtime);
        return this.create(transform, entity);
    }

    /**
     * @see net.malta.model.DeliveryAddressChoiseDao#create(net.malta.model.Choise, net.malta.model.DeliveryAddress, int, java.lang.String, java.lang.String)
     */
    public net.malta.model.DeliveryAddressChoise create(
        net.malta.model.Choise choise,
        net.malta.model.DeliveryAddress deliveryAddress,
        int ordernum,
        java.lang.String preferreddate,
        java.lang.String preferredtime)
    {
        return (net.malta.model.DeliveryAddressChoise)this.create(TRANSFORM_NONE, choise, deliveryAddress, ordernum, preferreddate, preferredtime);
    }

    /**
     * @see net.malta.model.DeliveryAddressChoiseDao#create(int, net.malta.model.Choise, net.malta.model.DeliveryAddress, int, java.lang.String, java.lang.String)
     */
    public java.lang.Object create(
        final int transform,
        net.malta.model.Choise choise,
        net.malta.model.DeliveryAddress deliveryAddress,
        int ordernum,
        java.lang.String preferreddate,
        java.lang.String preferredtime)
    {
        net.malta.model.DeliveryAddressChoise entity = new net.malta.model.DeliveryAddressChoiseImpl();
        entity.setChoise(choise);
        entity.setDeliveryAddress(deliveryAddress);
        entity.setOrdernum(ordernum);
        entity.setPreferreddate(preferreddate);
        entity.setPreferredtime(preferredtime);
        return this.create(transform, entity);
    }

    /**
     * @see net.malta.model.DeliveryAddressChoiseDao#update(net.malta.model.DeliveryAddressChoise)
     */
    public void update(net.malta.model.DeliveryAddressChoise deliveryAddressChoise)
    {
        if (deliveryAddressChoise == null)
        {
            throw new IllegalArgumentException(
                "DeliveryAddressChoise.update - 'deliveryAddressChoise' can not be null");
        }
        this.getHibernateTemplate().update(deliveryAddressChoise);
    }

    /**
     * @see net.malta.model.DeliveryAddressChoiseDao#update(java.util.Collection)
     */
    public void update(final java.util.Collection entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "DeliveryAddressChoise.update - 'entities' can not be null");
        }
        this.getHibernateTemplate().execute(
            new org.springframework.orm.hibernate3.HibernateCallback()
            {
                public java.lang.Object doInHibernate(org.hibernate.Session session)
                    throws org.hibernate.HibernateException
                {
                    for (java.util.Iterator entityIterator = entities.iterator(); entityIterator.hasNext();)
                    {
                        update((net.malta.model.DeliveryAddressChoise)entityIterator.next());
                    }
                    return null;
                }
            },
            true);
    }

    /**
     * @see net.malta.model.DeliveryAddressChoiseDao#remove(net.malta.model.DeliveryAddressChoise)
     */
    public void remove(net.malta.model.DeliveryAddressChoise deliveryAddressChoise)
    {
        if (deliveryAddressChoise == null)
        {
            throw new IllegalArgumentException(
                "DeliveryAddressChoise.remove - 'deliveryAddressChoise' can not be null");
        }
        this.getHibernateTemplate().delete(deliveryAddressChoise);
    }

    /**
     * @see net.malta.model.DeliveryAddressChoiseDao#remove(java.lang.Integer)
     */
    public void remove(java.lang.Integer id)
    {
        if (id == null)
        {
            throw new IllegalArgumentException(
                "DeliveryAddressChoise.remove - 'id' can not be null");
        }
        net.malta.model.DeliveryAddressChoise entity = this.load(id);
        if (entity != null)
        {
            this.remove(entity);
        }
    }

    /**
     * @see net.malta.model.DeliveryAddressChoiseDao#remove(java.util.Collection)
     */
    public void remove(java.util.Collection entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "DeliveryAddressChoise.remove - 'entities' can not be null");
        }
        this.getHibernateTemplate().deleteAll(entities);
    }
    /**
     * Allows transformation of entities into value objects
     * (or something else for that matter), when the <code>transform</code>
     * flag is set to one of the constants defined in <code>net.malta.model.DeliveryAddressChoiseDao</code>, please note
     * that the {@link #TRANSFORM_NONE} constant denotes no transformation, so the entity itself
     * will be returned.
     *
     * If the integer argument value is unknown {@link #TRANSFORM_NONE} is assumed.
     *
     * @param transform one of the constants declared in {@link net.malta.model.DeliveryAddressChoiseDao}
     * @param entity an entity that was found
     * @return the transformed entity (i.e. new value object, etc)
     * @see #transformEntities(int,java.util.Collection)
     */
    protected java.lang.Object transformEntity(final int transform, final net.malta.model.DeliveryAddressChoise entity)
    {
        java.lang.Object target = null;
        if (entity != null)
        {
            switch (transform)
            {
                case TRANSFORM_NONE : // fall-through
                default:
                    target = entity;
            }
        }
        return target;
    }

    /**
     * Transforms a collection of entities using the
     * {@link #transformEntity(int,net.malta.model.DeliveryAddressChoise)}
     * method. This method does not instantiate a new collection.
     * <p/>
     * This method is to be used internally only.
     *
     * @param transform one of the constants declared in <code>net.malta.model.DeliveryAddressChoiseDao</code>
     * @param entities the collection of entities to transform
     * @see #transformEntity(int,net.malta.model.DeliveryAddressChoise)
     */
    protected void transformEntities(final int transform, final java.util.Collection entities)
    {
        switch (transform)
        {
            case TRANSFORM_NONE : // fall-through
                default:
                // do nothing;
        }
    }

}