// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SpringHibernateDaoBase.vsl in andromda-spring-cartridge.
//
package net.malta.model;

/**
 * <p>
 * Base Spring DAO Class: is able to create, update, remove, load, and find
 * objects of type <code>net.malta.model.PublicUser</code>.
 * </p>
 *
 * @see net.malta.model.PublicUser
 */
public abstract class PublicUserDaoBase
    extends org.springframework.orm.hibernate3.support.HibernateDaoSupport
    implements net.malta.model.PublicUserDao
{

    /**
     * @see net.malta.model.PublicUserDao#load(int, java.lang.Integer)
     */
    public java.lang.Object load(final int transform, final java.lang.Integer id)
    {
        if (id == null)
        {
            throw new IllegalArgumentException(
                "PublicUser.load - 'id' can not be null");
        }
        final java.lang.Object entity = this.getHibernateTemplate().get(net.malta.model.PublicUserImpl.class, id);
        return transformEntity(transform, (net.malta.model.PublicUser)entity);
    }

    /**
     * @see net.malta.model.PublicUserDao#load(java.lang.Integer)
     */
    public net.malta.model.PublicUser load(java.lang.Integer id)
    {
        return (net.malta.model.PublicUser)this.load(TRANSFORM_NONE, id);
    }

    /**
     * @see net.malta.model.PublicUserDao#loadAll()
     */
    public java.util.Collection loadAll()
    {
        return this.loadAll(TRANSFORM_NONE);
    }

    /**
     * @see net.malta.model.PublicUserDao#loadAll(int)
     */
    public java.util.Collection loadAll(final int transform)
    {
        final java.util.Collection results = this.getHibernateTemplate().loadAll(net.malta.model.PublicUserImpl.class);
        this.transformEntities(transform, results);
        return results;
    }


    /**
     * @see net.malta.model.PublicUserDao#create(net.malta.model.PublicUser)
     */
    public net.malta.model.PublicUser create(net.malta.model.PublicUser publicUser)
    {
        return (net.malta.model.PublicUser)this.create(TRANSFORM_NONE, publicUser);
    }

    /**
     * @see net.malta.model.PublicUserDao#create(int transform, net.malta.model.PublicUser)
     */
    public java.lang.Object create(final int transform, final net.malta.model.PublicUser publicUser)
    {
        if (publicUser == null)
        {
            throw new IllegalArgumentException(
                "PublicUser.create - 'publicUser' can not be null");
        }
        this.getHibernateTemplate().save(publicUser);
        return this.transformEntity(transform, publicUser);
    }

    /**
     * @see net.malta.model.PublicUserDao#create(java.util.Collection)
     */
    public java.util.Collection create(final java.util.Collection entities)
    {
        return create(TRANSFORM_NONE, entities);
    }

    /**
     * @see net.malta.model.PublicUserDao#create(int, java.util.Collection)
     */
    public java.util.Collection create(final int transform, final java.util.Collection entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "PublicUser.create - 'entities' can not be null");
        }
        this.getHibernateTemplate().execute(
            new org.springframework.orm.hibernate3.HibernateCallback()
            {
                public java.lang.Object doInHibernate(org.hibernate.Session session)
                    throws org.hibernate.HibernateException
                {
                    for (java.util.Iterator entityIterator = entities.iterator(); entityIterator.hasNext();)
                    {
                        create(transform, (net.malta.model.PublicUser)entityIterator.next());
                    }
                    return null;
                }
            },
            true);
        return entities;
    }

    /**
     * @see net.malta.model.PublicUserDao#create(java.lang.String, java.lang.String, int, int, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, int, int, int, java.lang.String, java.lang.String, java.lang.String, java.lang.String, int, int, java.lang.String, boolean, boolean, int, int, java.lang.String, int, java.lang.String, boolean, java.lang.String, java.lang.String, boolean, boolean, java.lang.String)
     */
    public net.malta.model.PublicUser create(
        java.lang.String name,
        java.lang.String kana,
        int zipthree,
        int zipfour,
        java.lang.String pref,
        java.lang.String address,
        java.lang.String buildingname,
        java.lang.String mail,
        java.lang.String mailforconfirm,
        java.lang.String phone,
        int devliveryhour,
        int deliverydate,
        int deliveryphone,
        java.lang.String deliverykana,
        java.lang.String deliveryblocknumber,
        java.lang.String deliveryaddress,
        java.lang.String deliveryname,
        int deliveryzipfour,
        int deliveryzipthree,
        java.lang.String deliverypref,
        boolean delivertodifferentaddress,
        boolean male,
        int brithday,
        int birthmonth,
        java.lang.String municipality,
        int birthyear,
        java.lang.String keitai,
        boolean removed,
        java.lang.String password,
        java.lang.String fax,
        boolean registed,
        boolean temp,
        java.lang.String passwordonetimehash)
    {
        return (net.malta.model.PublicUser)this.create(TRANSFORM_NONE, name, kana, zipthree, zipfour, pref, address, buildingname, mail, mailforconfirm, phone, devliveryhour, deliverydate, deliveryphone, deliverykana, deliveryblocknumber, deliveryaddress, deliveryname, deliveryzipfour, deliveryzipthree, deliverypref, delivertodifferentaddress, male, brithday, birthmonth, municipality, birthyear, keitai, removed, password, fax, registed, temp, passwordonetimehash);
    }

    /**
     * @see net.malta.model.PublicUserDao#create(int, java.lang.String, java.lang.String, int, int, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, int, int, int, java.lang.String, java.lang.String, java.lang.String, java.lang.String, int, int, java.lang.String, boolean, boolean, int, int, java.lang.String, int, java.lang.String, boolean, java.lang.String, java.lang.String, boolean, boolean, java.lang.String)
     */
    public java.lang.Object create(
        final int transform,
        java.lang.String name,
        java.lang.String kana,
        int zipthree,
        int zipfour,
        java.lang.String pref,
        java.lang.String address,
        java.lang.String buildingname,
        java.lang.String mail,
        java.lang.String mailforconfirm,
        java.lang.String phone,
        int devliveryhour,
        int deliverydate,
        int deliveryphone,
        java.lang.String deliverykana,
        java.lang.String deliveryblocknumber,
        java.lang.String deliveryaddress,
        java.lang.String deliveryname,
        int deliveryzipfour,
        int deliveryzipthree,
        java.lang.String deliverypref,
        boolean delivertodifferentaddress,
        boolean male,
        int brithday,
        int birthmonth,
        java.lang.String municipality,
        int birthyear,
        java.lang.String keitai,
        boolean removed,
        java.lang.String password,
        java.lang.String fax,
        boolean registed,
        boolean temp,
        java.lang.String passwordonetimehash)
    {
        net.malta.model.PublicUser entity = new net.malta.model.PublicUserImpl();
        entity.setName(name);
        entity.setKana(kana);
        entity.setZipthree(zipthree);
        entity.setZipfour(zipfour);
        entity.setPref(pref);
        entity.setAddress(address);
        entity.setBuildingname(buildingname);
        entity.setMail(mail);
        entity.setMailforconfirm(mailforconfirm);
        entity.setPhone(phone);
        entity.setDevliveryhour(devliveryhour);
        entity.setDeliverydate(deliverydate);
        entity.setDeliveryphone(deliveryphone);
        entity.setDeliverykana(deliverykana);
        entity.setDeliveryblocknumber(deliveryblocknumber);
        entity.setDeliveryaddress(deliveryaddress);
        entity.setDeliveryname(deliveryname);
        entity.setDeliveryzipfour(deliveryzipfour);
        entity.setDeliveryzipthree(deliveryzipthree);
        entity.setDeliverypref(deliverypref);
        entity.setDelivertodifferentaddress(delivertodifferentaddress);
        entity.setMale(male);
        entity.setBrithday(brithday);
        entity.setBirthmonth(birthmonth);
        entity.setMunicipality(municipality);
        entity.setBirthyear(birthyear);
        entity.setKeitai(keitai);
        entity.setRemoved(removed);
        entity.setPassword(password);
        entity.setFax(fax);
        entity.setRegisted(registed);
        entity.setTemp(temp);
        entity.setPasswordonetimehash(passwordonetimehash);
        return this.create(transform, entity);
    }

    /**
     * @see net.malta.model.PublicUserDao#update(net.malta.model.PublicUser)
     */
    public void update(net.malta.model.PublicUser publicUser)
    {
        if (publicUser == null)
        {
            throw new IllegalArgumentException(
                "PublicUser.update - 'publicUser' can not be null");
        }
        this.getHibernateTemplate().update(publicUser);
    }

    /**
     * @see net.malta.model.PublicUserDao#update(java.util.Collection)
     */
    public void update(final java.util.Collection entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "PublicUser.update - 'entities' can not be null");
        }
        this.getHibernateTemplate().execute(
            new org.springframework.orm.hibernate3.HibernateCallback()
            {
                public java.lang.Object doInHibernate(org.hibernate.Session session)
                    throws org.hibernate.HibernateException
                {
                    for (java.util.Iterator entityIterator = entities.iterator(); entityIterator.hasNext();)
                    {
                        update((net.malta.model.PublicUser)entityIterator.next());
                    }
                    return null;
                }
            },
            true);
    }

    /**
     * @see net.malta.model.PublicUserDao#remove(net.malta.model.PublicUser)
     */
    public void remove(net.malta.model.PublicUser publicUser)
    {
        if (publicUser == null)
        {
            throw new IllegalArgumentException(
                "PublicUser.remove - 'publicUser' can not be null");
        }
        this.getHibernateTemplate().delete(publicUser);
    }

    /**
     * @see net.malta.model.PublicUserDao#remove(java.lang.Integer)
     */
    public void remove(java.lang.Integer id)
    {
        if (id == null)
        {
            throw new IllegalArgumentException(
                "PublicUser.remove - 'id' can not be null");
        }
        net.malta.model.PublicUser entity = this.load(id);
        if (entity != null)
        {
            this.remove(entity);
        }
    }

    /**
     * @see net.malta.model.PublicUserDao#remove(java.util.Collection)
     */
    public void remove(java.util.Collection entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "PublicUser.remove - 'entities' can not be null");
        }
        this.getHibernateTemplate().deleteAll(entities);
    }
    /**
     * Allows transformation of entities into value objects
     * (or something else for that matter), when the <code>transform</code>
     * flag is set to one of the constants defined in <code>net.malta.model.PublicUserDao</code>, please note
     * that the {@link #TRANSFORM_NONE} constant denotes no transformation, so the entity itself
     * will be returned.
     *
     * If the integer argument value is unknown {@link #TRANSFORM_NONE} is assumed.
     *
     * @param transform one of the constants declared in {@link net.malta.model.PublicUserDao}
     * @param entity an entity that was found
     * @return the transformed entity (i.e. new value object, etc)
     * @see #transformEntities(int,java.util.Collection)
     */
    protected java.lang.Object transformEntity(final int transform, final net.malta.model.PublicUser entity)
    {
        java.lang.Object target = null;
        if (entity != null)
        {
            switch (transform)
            {
                case TRANSFORM_NONE : // fall-through
                default:
                    target = entity;
            }
        }
        return target;
    }

    /**
     * Transforms a collection of entities using the
     * {@link #transformEntity(int,net.malta.model.PublicUser)}
     * method. This method does not instantiate a new collection.
     * <p/>
     * This method is to be used internally only.
     *
     * @param transform one of the constants declared in <code>net.malta.model.PublicUserDao</code>
     * @param entities the collection of entities to transform
     * @see #transformEntity(int,net.malta.model.PublicUser)
     */
    protected void transformEntities(final int transform, final java.util.Collection entities)
    {
        switch (transform)
        {
            case TRANSFORM_NONE : // fall-through
                default:
                // do nothing;
        }
    }

}