// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package net.malta.model;

/**
 * 
 */
public abstract class StaticData
    implements java.io.Serializable
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 8850815974513533305L;

    private java.lang.Integer id;

    /**
     * 
     */
    public java.lang.Integer getId()
    {
        return this.id;
    }

    public void setId(java.lang.Integer id)
    {
        this.id = id;
    }

    private java.lang.String fromaddress;

    /**
     * 
     */
    public java.lang.String getFromaddress()
    {
        return this.fromaddress;
    }

    public void setFromaddress(java.lang.String fromaddress)
    {
        this.fromaddress = fromaddress;
    }

    private java.lang.String sitename;

    /**
     * 
     */
    public java.lang.String getSitename()
    {
        return this.sitename;
    }

    public void setSitename(java.lang.String sitename)
    {
        this.sitename = sitename;
    }

    private java.lang.String basepath;

    /**
     * 
     */
    public java.lang.String getBasepath()
    {
        return this.basepath;
    }

    public void setBasepath(java.lang.String basepath)
    {
        this.basepath = basepath;
    }

    private boolean unix;

    /**
     * 
     */
    public boolean isUnix()
    {
        return this.unix;
    }

    public void setUnix(boolean unix)
    {
        this.unix = unix;
    }

    private int mapeventspan;

    /**
     * 
     */
    public int getMapeventspan()
    {
        return this.mapeventspan;
    }

    public void setMapeventspan(int mapeventspan)
    {
        this.mapeventspan = mapeventspan;
    }

    private byte[] noimage;

    /**
     * 
     */
    public byte[] getNoimage()
    {
        return this.noimage;
    }

    public void setNoimage(byte[] noimage)
    {
        this.noimage = noimage;
    }

    private int carriage;

    /**
     * 
     */
    public int getCarriage()
    {
        return this.carriage;
    }

    public void setCarriage(int carriage)
    {
        this.carriage = carriage;
    }

    private java.lang.String creditcardprocesurl;

    /**
     * 
     */
    public java.lang.String getCreditcardprocesurl()
    {
        return this.creditcardprocesurl;
    }

    public void setCreditcardprocesurl(java.lang.String creditcardprocesurl)
    {
        this.creditcardprocesurl = creditcardprocesurl;
    }

    private java.lang.String contract_code;

    /**
     * 
     */
    public java.lang.String getContract_code()
    {
        return this.contract_code;
    }

    public void setContract_code(java.lang.String contract_code)
    {
        this.contract_code = contract_code;
    }

    /**
     * Returns <code>true</code> if the argument is an StaticData instance and all identifiers for this entity
     * equal the identifiers of the argument entity. Returns <code>false</code> otherwise.
     */
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof StaticData))
        {
            return false;
        }
        final StaticData that = (StaticData)object;
        if (this.id == null || that.getId() == null || !this.id.equals(that.getId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code based on this entity's identifiers.
     */
    public int hashCode()
    {
        int hashCode = 0;
        hashCode = 29 * hashCode + (id == null ? 0 : id.hashCode());

        return hashCode;
    }

    /**
     * Constructs new instances of {@link net.malta.model.StaticData}.
     */
    public static final class Factory
    {
        /**
         * Constructs a new instance of {@link net.malta.model.StaticData}.
         */
        public static net.malta.model.StaticData newInstance()
        {
            return new net.malta.model.StaticDataImpl();
        }


        /**
         * Constructs a new instance of {@link net.malta.model.StaticData}, taking all possible properties
         * (except the identifier(s))as arguments.
         */
        public static net.malta.model.StaticData newInstance(java.lang.String fromaddress, java.lang.String sitename, java.lang.String basepath, boolean unix, int mapeventspan, byte[] noimage, int carriage, java.lang.String creditcardprocesurl, java.lang.String contract_code)
        {
            final net.malta.model.StaticData entity = new net.malta.model.StaticDataImpl();
            entity.setFromaddress(fromaddress);
            entity.setSitename(sitename);
            entity.setBasepath(basepath);
            entity.setUnix(unix);
            entity.setMapeventspan(mapeventspan);
            entity.setNoimage(noimage);
            entity.setCarriage(carriage);
            entity.setCreditcardprocesurl(creditcardprocesurl);
            entity.setContract_code(contract_code);
            return entity;
        }
    }
    
// HibernateEntity.vsl merge-point
}