// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SpringHibernateDaoImpl.vsl in andromda-spring-cartridge.
//
package net.malta.model;
/**
 * @see net.malta.model.Attachment
 */
public class AttachmentDaoImpl
    extends net.malta.model.AttachmentDaoBase
{
}