// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package net.malta.model;

/**
 * 
 */
public abstract class Carriage
    implements java.io.Serializable
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -4346247960187448183L;

    private java.lang.Integer id;

    /**
     * 
     */
    public java.lang.Integer getId()
    {
        return this.id;
    }

    public void setId(java.lang.Integer id)
    {
        this.id = id;
    }

    private java.lang.String name;

    /**
     * 
     */
    public java.lang.String getName()
    {
        return this.name;
    }

    public void setName(java.lang.String name)
    {
        this.name = name;
    }

    private int value;

    /**
     * 
     */
    public int getValue()
    {
        return this.value;
    }

    public void setValue(int value)
    {
        this.value = value;
    }

    private java.util.Collection items = new java.util.HashSet();

    /**
     * 
     */
    public java.util.Collection getItems()
    {
        return this.items;
    }

    public void setItems(java.util.Collection items)
    {
        this.items = items;
    }

    /**
     * Returns <code>true</code> if the argument is an Carriage instance and all identifiers for this entity
     * equal the identifiers of the argument entity. Returns <code>false</code> otherwise.
     */
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof Carriage))
        {
            return false;
        }
        final Carriage that = (Carriage)object;
        if (this.id == null || that.getId() == null || !this.id.equals(that.getId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code based on this entity's identifiers.
     */
    public int hashCode()
    {
        int hashCode = 0;
        hashCode = 29 * hashCode + (id == null ? 0 : id.hashCode());

        return hashCode;
    }

    /**
     * Constructs new instances of {@link net.malta.model.Carriage}.
     */
    public static final class Factory
    {
        /**
         * Constructs a new instance of {@link net.malta.model.Carriage}.
         */
        public static net.malta.model.Carriage newInstance()
        {
            return new net.malta.model.CarriageImpl();
        }

        /**
         * Constructs a new instance of {@link net.malta.model.Carriage}, taking all required and/or
         * read-only properties as arguments.
         */
        public static net.malta.model.Carriage newInstance(java.lang.String name, int value)
        {
            final net.malta.model.Carriage entity = new net.malta.model.CarriageImpl();
            entity.setName(name);
            entity.setValue(value);
            return entity;
        }

        /**
         * Constructs a new instance of {@link net.malta.model.Carriage}, taking all possible properties
         * (except the identifier(s))as arguments.
         */
        public static net.malta.model.Carriage newInstance(java.lang.String name, int value, java.util.Collection items)
        {
            final net.malta.model.Carriage entity = new net.malta.model.CarriageImpl();
            entity.setName(name);
            entity.setValue(value);
            entity.setItems(items);
            return entity;
        }
    }
    
// HibernateEntity.vsl merge-point
}