// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package net.malta.model;

/**
 * @see net.malta.model.DeliveryAddress
 */
public class DeliveryAddressImpl
    extends net.malta.model.DeliveryAddress
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 7192773678198672507L;

}