// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package net.malta.model;

/**
 * @see net.malta.model.DeliveryAddressChoise
 */
public class DeliveryAddressChoiseImpl
    extends net.malta.model.DeliveryAddressChoise
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -4732361222348013500L;

}