// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SpringHibernateDaoBase.vsl in andromda-spring-cartridge.
//
package net.malta.model;

/**
 * <p>
 * Base Spring DAO Class: is able to create, update, remove, load, and find
 * objects of type <code>net.malta.model.DeliveryAddress</code>.
 * </p>
 *
 * @see net.malta.model.DeliveryAddress
 */
public abstract class DeliveryAddressDaoBase
    extends org.springframework.orm.hibernate3.support.HibernateDaoSupport
    implements net.malta.model.DeliveryAddressDao
{

    /**
     * @see net.malta.model.DeliveryAddressDao#load(int, java.lang.Integer)
     */
    public java.lang.Object load(final int transform, final java.lang.Integer id)
    {
        if (id == null)
        {
            throw new IllegalArgumentException(
                "DeliveryAddress.load - 'id' can not be null");
        }
        final java.lang.Object entity = this.getHibernateTemplate().get(net.malta.model.DeliveryAddressImpl.class, id);
        return transformEntity(transform, (net.malta.model.DeliveryAddress)entity);
    }

    /**
     * @see net.malta.model.DeliveryAddressDao#load(java.lang.Integer)
     */
    public net.malta.model.DeliveryAddress load(java.lang.Integer id)
    {
        return (net.malta.model.DeliveryAddress)this.load(TRANSFORM_NONE, id);
    }

    /**
     * @see net.malta.model.DeliveryAddressDao#loadAll()
     */
    public java.util.Collection loadAll()
    {
        return this.loadAll(TRANSFORM_NONE);
    }

    /**
     * @see net.malta.model.DeliveryAddressDao#loadAll(int)
     */
    public java.util.Collection loadAll(final int transform)
    {
        final java.util.Collection results = this.getHibernateTemplate().loadAll(net.malta.model.DeliveryAddressImpl.class);
        this.transformEntities(transform, results);
        return results;
    }


    /**
     * @see net.malta.model.DeliveryAddressDao#create(net.malta.model.DeliveryAddress)
     */
    public net.malta.model.DeliveryAddress create(net.malta.model.DeliveryAddress deliveryAddress)
    {
        return (net.malta.model.DeliveryAddress)this.create(TRANSFORM_NONE, deliveryAddress);
    }

    /**
     * @see net.malta.model.DeliveryAddressDao#create(int transform, net.malta.model.DeliveryAddress)
     */
    public java.lang.Object create(final int transform, final net.malta.model.DeliveryAddress deliveryAddress)
    {
        if (deliveryAddress == null)
        {
            throw new IllegalArgumentException(
                "DeliveryAddress.create - 'deliveryAddress' can not be null");
        }
        this.getHibernateTemplate().save(deliveryAddress);
        return this.transformEntity(transform, deliveryAddress);
    }

    /**
     * @see net.malta.model.DeliveryAddressDao#create(java.util.Collection)
     */
    public java.util.Collection create(final java.util.Collection entities)
    {
        return create(TRANSFORM_NONE, entities);
    }

    /**
     * @see net.malta.model.DeliveryAddressDao#create(int, java.util.Collection)
     */
    public java.util.Collection create(final int transform, final java.util.Collection entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "DeliveryAddress.create - 'entities' can not be null");
        }
        this.getHibernateTemplate().execute(
            new org.springframework.orm.hibernate3.HibernateCallback()
            {
                public java.lang.Object doInHibernate(org.hibernate.Session session)
                    throws org.hibernate.HibernateException
                {
                    for (java.util.Iterator entityIterator = entities.iterator(); entityIterator.hasNext();)
                    {
                        create(transform, (net.malta.model.DeliveryAddress)entityIterator.next());
                    }
                    return null;
                }
            },
            true);
        return entities;
    }

    /**
     * @see net.malta.model.DeliveryAddressDao#create(java.lang.String, java.lang.String, int, int, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, boolean)
     */
    public net.malta.model.DeliveryAddress create(
        java.lang.String name,
        java.lang.String kana,
        int zipthree,
        int zipfour,
        java.lang.String phone,
        java.lang.String address,
        java.lang.String buildingname,
        java.lang.String pref,
        java.lang.String preferreddate,
        java.lang.String preferredtime,
        boolean hasgiftcard)
    {
        return (net.malta.model.DeliveryAddress)this.create(TRANSFORM_NONE, name, kana, zipthree, zipfour, phone, address, buildingname, pref, preferreddate, preferredtime, hasgiftcard);
    }

    /**
     * @see net.malta.model.DeliveryAddressDao#create(int, java.lang.String, java.lang.String, int, int, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, boolean)
     */
    public java.lang.Object create(
        final int transform,
        java.lang.String name,
        java.lang.String kana,
        int zipthree,
        int zipfour,
        java.lang.String phone,
        java.lang.String address,
        java.lang.String buildingname,
        java.lang.String pref,
        java.lang.String preferreddate,
        java.lang.String preferredtime,
        boolean hasgiftcard)
    {
        net.malta.model.DeliveryAddress entity = new net.malta.model.DeliveryAddressImpl();
        entity.setName(name);
        entity.setKana(kana);
        entity.setZipthree(zipthree);
        entity.setZipfour(zipfour);
        entity.setPhone(phone);
        entity.setAddress(address);
        entity.setBuildingname(buildingname);
        entity.setPref(pref);
        entity.setPreferreddate(preferreddate);
        entity.setPreferredtime(preferredtime);
        entity.setHasgiftcard(hasgiftcard);
        return this.create(transform, entity);
    }

    /**
     * @see net.malta.model.DeliveryAddressDao#create(java.lang.String, java.lang.String, boolean, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, net.malta.model.PublicUser, int, int)
     */
    public net.malta.model.DeliveryAddress create(
        java.lang.String address,
        java.lang.String buildingname,
        boolean hasgiftcard,
        java.lang.String kana,
        java.lang.String name,
        java.lang.String phone,
        java.lang.String pref,
        java.lang.String preferreddate,
        java.lang.String preferredtime,
        net.malta.model.PublicUser publicUser,
        int zipfour,
        int zipthree)
    {
        return (net.malta.model.DeliveryAddress)this.create(TRANSFORM_NONE, address, buildingname, hasgiftcard, kana, name, phone, pref, preferreddate, preferredtime, publicUser, zipfour, zipthree);
    }

    /**
     * @see net.malta.model.DeliveryAddressDao#create(int, java.lang.String, java.lang.String, boolean, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, net.malta.model.PublicUser, int, int)
     */
    public java.lang.Object create(
        final int transform,
        java.lang.String address,
        java.lang.String buildingname,
        boolean hasgiftcard,
        java.lang.String kana,
        java.lang.String name,
        java.lang.String phone,
        java.lang.String pref,
        java.lang.String preferreddate,
        java.lang.String preferredtime,
        net.malta.model.PublicUser publicUser,
        int zipfour,
        int zipthree)
    {
        net.malta.model.DeliveryAddress entity = new net.malta.model.DeliveryAddressImpl();
        entity.setAddress(address);
        entity.setBuildingname(buildingname);
        entity.setHasgiftcard(hasgiftcard);
        entity.setKana(kana);
        entity.setName(name);
        entity.setPhone(phone);
        entity.setPref(pref);
        entity.setPreferreddate(preferreddate);
        entity.setPreferredtime(preferredtime);
        entity.setPublicUser(publicUser);
        entity.setZipfour(zipfour);
        entity.setZipthree(zipthree);
        return this.create(transform, entity);
    }

    /**
     * @see net.malta.model.DeliveryAddressDao#update(net.malta.model.DeliveryAddress)
     */
    public void update(net.malta.model.DeliveryAddress deliveryAddress)
    {
        if (deliveryAddress == null)
        {
            throw new IllegalArgumentException(
                "DeliveryAddress.update - 'deliveryAddress' can not be null");
        }
        this.getHibernateTemplate().update(deliveryAddress);
    }

    /**
     * @see net.malta.model.DeliveryAddressDao#update(java.util.Collection)
     */
    public void update(final java.util.Collection entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "DeliveryAddress.update - 'entities' can not be null");
        }
        this.getHibernateTemplate().execute(
            new org.springframework.orm.hibernate3.HibernateCallback()
            {
                public java.lang.Object doInHibernate(org.hibernate.Session session)
                    throws org.hibernate.HibernateException
                {
                    for (java.util.Iterator entityIterator = entities.iterator(); entityIterator.hasNext();)
                    {
                        update((net.malta.model.DeliveryAddress)entityIterator.next());
                    }
                    return null;
                }
            },
            true);
    }

    /**
     * @see net.malta.model.DeliveryAddressDao#remove(net.malta.model.DeliveryAddress)
     */
    public void remove(net.malta.model.DeliveryAddress deliveryAddress)
    {
        if (deliveryAddress == null)
        {
            throw new IllegalArgumentException(
                "DeliveryAddress.remove - 'deliveryAddress' can not be null");
        }
        this.getHibernateTemplate().delete(deliveryAddress);
    }

    /**
     * @see net.malta.model.DeliveryAddressDao#remove(java.lang.Integer)
     */
    public void remove(java.lang.Integer id)
    {
        if (id == null)
        {
            throw new IllegalArgumentException(
                "DeliveryAddress.remove - 'id' can not be null");
        }
        net.malta.model.DeliveryAddress entity = this.load(id);
        if (entity != null)
        {
            this.remove(entity);
        }
    }

    /**
     * @see net.malta.model.DeliveryAddressDao#remove(java.util.Collection)
     */
    public void remove(java.util.Collection entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "DeliveryAddress.remove - 'entities' can not be null");
        }
        this.getHibernateTemplate().deleteAll(entities);
    }
    /**
     * Allows transformation of entities into value objects
     * (or something else for that matter), when the <code>transform</code>
     * flag is set to one of the constants defined in <code>net.malta.model.DeliveryAddressDao</code>, please note
     * that the {@link #TRANSFORM_NONE} constant denotes no transformation, so the entity itself
     * will be returned.
     *
     * If the integer argument value is unknown {@link #TRANSFORM_NONE} is assumed.
     *
     * @param transform one of the constants declared in {@link net.malta.model.DeliveryAddressDao}
     * @param entity an entity that was found
     * @return the transformed entity (i.e. new value object, etc)
     * @see #transformEntities(int,java.util.Collection)
     */
    protected java.lang.Object transformEntity(final int transform, final net.malta.model.DeliveryAddress entity)
    {
        java.lang.Object target = null;
        if (entity != null)
        {
            switch (transform)
            {
                case TRANSFORM_NONE : // fall-through
                default:
                    target = entity;
            }
        }
        return target;
    }

    /**
     * Transforms a collection of entities using the
     * {@link #transformEntity(int,net.malta.model.DeliveryAddress)}
     * method. This method does not instantiate a new collection.
     * <p/>
     * This method is to be used internally only.
     *
     * @param transform one of the constants declared in <code>net.malta.model.DeliveryAddressDao</code>
     * @param entities the collection of entities to transform
     * @see #transformEntity(int,net.malta.model.DeliveryAddress)
     */
    protected void transformEntities(final int transform, final java.util.Collection entities)
    {
        switch (transform)
        {
            case TRANSFORM_NONE : // fall-through
                default:
                // do nothing;
        }
    }

}