// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package net.malta.model;

/**
 * 
 */
public abstract class PaymentMethod
    implements java.io.Serializable
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 930364057375739439L;

    private java.lang.Integer id;

    /**
     * 
     */
    public java.lang.Integer getId()
    {
        return this.id;
    }

    public void setId(java.lang.Integer id)
    {
        this.id = id;
    }

    private java.lang.String name;

    /**
     * 
     */
    public java.lang.String getName()
    {
        return this.name;
    }

    public void setName(java.lang.String name)
    {
        this.name = name;
    }

    private java.lang.String note;

    /**
     * 
     */
    public java.lang.String getNote()
    {
        return this.note;
    }

    public void setNote(java.lang.String note)
    {
        this.note = note;
    }

    private java.util.Collection purchases = new java.util.HashSet();

    /**
     * 
     */
    public java.util.Collection getPurchases()
    {
        return this.purchases;
    }

    public void setPurchases(java.util.Collection purchases)
    {
        this.purchases = purchases;
    }

    /**
     * Returns <code>true</code> if the argument is an PaymentMethod instance and all identifiers for this entity
     * equal the identifiers of the argument entity. Returns <code>false</code> otherwise.
     */
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof PaymentMethod))
        {
            return false;
        }
        final PaymentMethod that = (PaymentMethod)object;
        if (this.id == null || that.getId() == null || !this.id.equals(that.getId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code based on this entity's identifiers.
     */
    public int hashCode()
    {
        int hashCode = 0;
        hashCode = 29 * hashCode + (id == null ? 0 : id.hashCode());

        return hashCode;
    }

    /**
     * Constructs new instances of {@link net.malta.model.PaymentMethod}.
     */
    public static final class Factory
    {
        /**
         * Constructs a new instance of {@link net.malta.model.PaymentMethod}.
         */
        public static net.malta.model.PaymentMethod newInstance()
        {
            return new net.malta.model.PaymentMethodImpl();
        }

        /**
         * Constructs a new instance of {@link net.malta.model.PaymentMethod}, taking all required and/or
         * read-only properties as arguments.
         */
        public static net.malta.model.PaymentMethod newInstance(java.lang.String name, java.lang.String note)
        {
            final net.malta.model.PaymentMethod entity = new net.malta.model.PaymentMethodImpl();
            entity.setName(name);
            entity.setNote(note);
            return entity;
        }

        /**
         * Constructs a new instance of {@link net.malta.model.PaymentMethod}, taking all possible properties
         * (except the identifier(s))as arguments.
         */
        public static net.malta.model.PaymentMethod newInstance(java.lang.String name, java.lang.String note, java.util.Collection purchases)
        {
            final net.malta.model.PaymentMethod entity = new net.malta.model.PaymentMethodImpl();
            entity.setName(name);
            entity.setNote(note);
            entity.setPurchases(purchases);
            return entity;
        }
    }
    
// HibernateEntity.vsl merge-point
}