// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SpringHibernateDaoBase.vsl in andromda-spring-cartridge.
//
package net.malta.model;

/**
 * <p>
 * Base Spring DAO Class: is able to create, update, remove, load, and find
 * objects of type <code>net.malta.model.Purchase</code>.
 * </p>
 *
 * @see net.malta.model.Purchase
 */
public abstract class PurchaseDaoBase
    extends org.springframework.orm.hibernate3.support.HibernateDaoSupport
    implements net.malta.model.PurchaseDao
{

    /**
     * @see net.malta.model.PurchaseDao#load(int, java.lang.Integer)
     */
    public java.lang.Object load(final int transform, final java.lang.Integer id)
    {
        if (id == null)
        {
            throw new IllegalArgumentException(
                "Purchase.load - 'id' can not be null");
        }
        final java.lang.Object entity = this.getHibernateTemplate().get(net.malta.model.PurchaseImpl.class, id);
        return transformEntity(transform, (net.malta.model.Purchase)entity);
    }

    /**
     * @see net.malta.model.PurchaseDao#load(java.lang.Integer)
     */
    public net.malta.model.Purchase load(java.lang.Integer id)
    {
        return (net.malta.model.Purchase)this.load(TRANSFORM_NONE, id);
    }

    /**
     * @see net.malta.model.PurchaseDao#loadAll()
     */
    public java.util.Collection loadAll()
    {
        return this.loadAll(TRANSFORM_NONE);
    }

    /**
     * @see net.malta.model.PurchaseDao#loadAll(int)
     */
    public java.util.Collection loadAll(final int transform)
    {
        final java.util.Collection results = this.getHibernateTemplate().loadAll(net.malta.model.PurchaseImpl.class);
        this.transformEntities(transform, results);
        return results;
    }


    /**
     * @see net.malta.model.PurchaseDao#create(net.malta.model.Purchase)
     */
    public net.malta.model.Purchase create(net.malta.model.Purchase purchase)
    {
        return (net.malta.model.Purchase)this.create(TRANSFORM_NONE, purchase);
    }

    /**
     * @see net.malta.model.PurchaseDao#create(int transform, net.malta.model.Purchase)
     */
    public java.lang.Object create(final int transform, final net.malta.model.Purchase purchase)
    {
        if (purchase == null)
        {
            throw new IllegalArgumentException(
                "Purchase.create - 'purchase' can not be null");
        }
        this.getHibernateTemplate().save(purchase);
        return this.transformEntity(transform, purchase);
    }

    /**
     * @see net.malta.model.PurchaseDao#create(java.util.Collection)
     */
    public java.util.Collection create(final java.util.Collection entities)
    {
        return create(TRANSFORM_NONE, entities);
    }

    /**
     * @see net.malta.model.PurchaseDao#create(int, java.util.Collection)
     */
    public java.util.Collection create(final int transform, final java.util.Collection entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "Purchase.create - 'entities' can not be null");
        }
        this.getHibernateTemplate().execute(
            new org.springframework.orm.hibernate3.HibernateCallback()
            {
                public java.lang.Object doInHibernate(org.hibernate.Session session)
                    throws org.hibernate.HibernateException
                {
                    for (java.util.Iterator entityIterator = entities.iterator(); entityIterator.hasNext();)
                    {
                        create(transform, (net.malta.model.Purchase)entityIterator.next());
                    }
                    return null;
                }
            },
            true);
        return entities;
    }

    /**
     * @see net.malta.model.PurchaseDao#create(int, int, int, boolean, java.util.Date, boolean, boolean, boolean)
     */
    public net.malta.model.Purchase create(
        int total,
        int carriage,
        int totalordernum,
        boolean shipped,
        java.util.Date date,
        boolean temp,
        boolean cancelled,
        boolean removed)
    {
        return (net.malta.model.Purchase)this.create(TRANSFORM_NONE, total, carriage, totalordernum, shipped, date, temp, cancelled, removed);
    }

    /**
     * @see net.malta.model.PurchaseDao#create(int, int, int, int, boolean, java.util.Date, boolean, boolean, boolean)
     */
    public java.lang.Object create(
        final int transform,
        int total,
        int carriage,
        int totalordernum,
        boolean shipped,
        java.util.Date date,
        boolean temp,
        boolean cancelled,
        boolean removed)
    {
        net.malta.model.Purchase entity = new net.malta.model.PurchaseImpl();
        entity.setTotal(total);
        entity.setCarriage(carriage);
        entity.setTotalordernum(totalordernum);
        entity.setShipped(shipped);
        entity.setDate(date);
        entity.setTemp(temp);
        entity.setCancelled(cancelled);
        entity.setRemoved(removed);
        return this.create(transform, entity);
    }

    /**
     * @see net.malta.model.PurchaseDao#update(net.malta.model.Purchase)
     */
    public void update(net.malta.model.Purchase purchase)
    {
        if (purchase == null)
        {
            throw new IllegalArgumentException(
                "Purchase.update - 'purchase' can not be null");
        }
        this.getHibernateTemplate().update(purchase);
    }

    /**
     * @see net.malta.model.PurchaseDao#update(java.util.Collection)
     */
    public void update(final java.util.Collection entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "Purchase.update - 'entities' can not be null");
        }
        this.getHibernateTemplate().execute(
            new org.springframework.orm.hibernate3.HibernateCallback()
            {
                public java.lang.Object doInHibernate(org.hibernate.Session session)
                    throws org.hibernate.HibernateException
                {
                    for (java.util.Iterator entityIterator = entities.iterator(); entityIterator.hasNext();)
                    {
                        update((net.malta.model.Purchase)entityIterator.next());
                    }
                    return null;
                }
            },
            true);
    }

    /**
     * @see net.malta.model.PurchaseDao#remove(net.malta.model.Purchase)
     */
    public void remove(net.malta.model.Purchase purchase)
    {
        if (purchase == null)
        {
            throw new IllegalArgumentException(
                "Purchase.remove - 'purchase' can not be null");
        }
        this.getHibernateTemplate().delete(purchase);
    }

    /**
     * @see net.malta.model.PurchaseDao#remove(java.lang.Integer)
     */
    public void remove(java.lang.Integer id)
    {
        if (id == null)
        {
            throw new IllegalArgumentException(
                "Purchase.remove - 'id' can not be null");
        }
        net.malta.model.Purchase entity = this.load(id);
        if (entity != null)
        {
            this.remove(entity);
        }
    }

    /**
     * @see net.malta.model.PurchaseDao#remove(java.util.Collection)
     */
    public void remove(java.util.Collection entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "Purchase.remove - 'entities' can not be null");
        }
        this.getHibernateTemplate().deleteAll(entities);
    }
    /**
     * Allows transformation of entities into value objects
     * (or something else for that matter), when the <code>transform</code>
     * flag is set to one of the constants defined in <code>net.malta.model.PurchaseDao</code>, please note
     * that the {@link #TRANSFORM_NONE} constant denotes no transformation, so the entity itself
     * will be returned.
     *
     * If the integer argument value is unknown {@link #TRANSFORM_NONE} is assumed.
     *
     * @param transform one of the constants declared in {@link net.malta.model.PurchaseDao}
     * @param entity an entity that was found
     * @return the transformed entity (i.e. new value object, etc)
     * @see #transformEntities(int,java.util.Collection)
     */
    protected java.lang.Object transformEntity(final int transform, final net.malta.model.Purchase entity)
    {
        java.lang.Object target = null;
        if (entity != null)
        {
            switch (transform)
            {
                case TRANSFORM_NONE : // fall-through
                default:
                    target = entity;
            }
        }
        return target;
    }

    /**
     * Transforms a collection of entities using the
     * {@link #transformEntity(int,net.malta.model.Purchase)}
     * method. This method does not instantiate a new collection.
     * <p/>
     * This method is to be used internally only.
     *
     * @param transform one of the constants declared in <code>net.malta.model.PurchaseDao</code>
     * @param entities the collection of entities to transform
     * @see #transformEntity(int,net.malta.model.Purchase)
     */
    protected void transformEntities(final int transform, final java.util.Collection entities)
    {
        switch (transform)
        {
            case TRANSFORM_NONE : // fall-through
                default:
                // do nothing;
        }
    }

}