ALTER TABLE PRODUCT
ADD COLUMN ENGLISH VARCHAR(255);

ALTER TABLE CHOISE
ADD COLUMN CARRIAGE INT NULL AFTER ITEM_FK;

ALTER TABLE CHOISE
ADD COLUMN NAME INT NULL AFTER CARRIAGE;

ALTER TABLE CHOISE
ADD COLUMN VARIETYCHOISE VARCHAR(255) NULL AFTER NAME;

ALTER TABLE CHOISE
ADD COLUMN IMG VARCHAR(255) BINARY NULL AFTER VARIETYCHOISE;

ALTER TABLE CHOISE
ADD COLUMN wp_posts_id INT NULL AFTER IMG;