ALTER TABLE malta.product
ADD COLUMN ENGLISH VARCHAR(255);

ALTER TABLE malta.choise
ADD COLUMN CARRIAGE INT NULL AFTER ITEM_FK;

ALTER TABLE malta.choise
ADD COLUMN NAME INT NULL AFTER CARRIAGE;

ALTER TABLE malta.choise
ADD COLUMN VARIETYCHOISE VARCHAR(255) NULL AFTER NAME;

ALTER TABLE malta.choise
ADD COLUMN IMG VARCHAR(255) BINARY NULL AFTER VARIETYCHOISE;

ALTER TABLE malta.choise
ADD COLUMN wp_posts_id INT NULL AFTER IMG;